blog/urls.py
from django.urls import path    
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.posts, name='all-posts'),
    path('posts/<slug:slug>',views.post_detail, name='post-detail-page')
]

jagger_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

class Tag(models.Model):
    caption = models.CharField(max_length=20)

    def __str__(self) -> str:
        return f"{self.caption}"

class Post(models.Model):
    title = models.CharField(max_length=150)
    excerpt = models.CharField(max_length=200)
    image_name = models.CharField(max_length=100)
    date = models.DateField(auto_now=True)
    slug = models.SlugField(unique=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL, related_name="posts")
    tags = models.ManyToManyField(Tag)

    def __str__(self) -> str:
        return f"{self.date} {self.title}"

    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def index(request):
    all_posts = Post.objects.all().order_by("-date")[:3]
    return render(request, 'blog/index.html',{'posts':all_posts})

def posts(request):
    all_posts = Post.objects.all()
    return render(request, 'blog/posts.html',{"posts":all_posts})

def post_detail(request, slug):
    desired_post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post-detail.html',{'post':desired_post})

jagger_site/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

blog/templates/blog/components/navigation-header.html
<header id="main-navigation">
    <h1><a href="{% url 'index' %}">Andy's Blog</a></h1>
    <nav>
        <a href="{% url 'blog:all-posts' %}">All posts</a>
    </nav>
</header>

blog/templates/blog/components/post-card.html
{% load static %}
<li>
    <article class="post">
        <a href="{% url "blog:post-detail-page" slug=post.slug%}">
            <img src="{% static "blog/images/"|add:post.image %}" alt="Mountain" />
            <div class="post-content">
                <h3>{{post.title}}</h3>
                <p>
                    {{post.excerpt}}
                </p>
            </div>
        </a>
    </article>
</li>

blog/templates/blog/post-detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
This block title
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static "blog/post-detail.css"%}">
{% endblock  %}



{% block content %}

{% include "blog/components/navigation-header.html" %}

<section id="summary">
    <h2>{{post.title}}</h2>
    <article>
        <img src="{% static "blog/images/"|add:post.image_name %}" alt="Post title">
        <address>By {{post.author}}</address>
        <div>
            Last updated on <time datetime="">{{post.date|date:'d M Y'}}</time>
        </div>
    </article>
</section>

<main>
    <p>
        {{post.content|linebreaks}}
    </p>
</main>
{% endblock  %}

blog/templates/blog/posts.html
{% extends 'base.html' %}

{% load static %}

{% block css_files%}

<link rel="stylesheet" href="{% static "blog/index.css"%}">
<link rel="stylesheet" href="{% static "blog/post.css"%}">
<link rel="stylesheet" href="{% static "blog/all-posts.css"%}">

{% endblock %}

{% block title %}
Andy's Blog
{% endblock  %}


{% block content %}

{% include "blog/components/navigation-header.html" %}

<section id="all-posts">
    <h2>My Collected Posts</h2>
    <ul>
        {% for post in posts %}
        {% include "blog/components/post-card.html" %}
        {% endfor %}
    </ul>
</section>

{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="description" content="This is a blog about technology and the world">
    <meta name="keywords" content="technology, blog, programming, django">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}{% endblock  %}
    </title>

    <link rel="stylesheet" href="{% static "global.css"%}">
    {%block css_files%}{% endblock %}
</head>

<body>
    {% block content%}{% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block css_files%}

<link rel="stylesheet" href="{% static "blog/index.css"%}">
<link rel="stylesheet" href="{% static "blog/post.css"%}">
{% endblock %}

{% block title %}
Andy's Blog
{% endblock  %}

{% block content %}

{% include "blog/components/navigation-header.html" %}

<section id="welcome">
    <header>
        <img src="{% static "blog/images/andy.jpeg"%}" alt="Andy the author of this blog">
    </header>
    <p>Hi, I am andy and I love to blog about tech and the world</p>
</section>

<section id="latest-posts">
    <h2>My Latest Articles</h2>
    <ul>
        {% for post in posts %}
        {% include "blog/components/post-card.html" %}
        {% endfor %}
    </ul>
</section>

<section id="about">
    <h2>What I do </h2>
    <p>I love programming, I love to help others and enjoy exploring new technologies </p>
    <p>My goal is to keep growing as a developer</p>
</section>

{% endblock %}